### ISSUE TITLE
LGUI(KC_LSFT) does not work

### ISSUE THREAD

**Issue by sboesebeck** [jackhumbert/qmk_firmware#221]
Hi,

when defining a key to be LGUI(KC_LSFT) it remains pressed until I hit another key. Then LGUI is switched off and only LSFT is pressed... so instead of LGUI_LSFT_N you type LSFT_N

when swapping LGUI and LSFT the behavior is similar, only LSFT is dropped out and only LGUI being pressed...

Hope this makes sense of some kind ;-)

**Comment by sboesebeck** [comment]
I added a macro doing the same, that worked fine

**Comment by ezuk** [comment]
@jackhumbert any reason why this wouldn't work? I think the weak mods PR fixed it?

**Comment by DidierLoiseau** [comment]
I think #188 broke this usage, which I had never thought of. For me the usage of `LSFT`, `LGUI` etc. is designed to only affect a single key press, not the next ones.

It could make sense to apply a different behavior when those are applied to `KC_LSFT` etc., by using the normal mods instead of the weak mods for example.

Note that the PR was especially designed to allow this usage through macros though.

**Comment by sboesebeck** [comment]
Hi - I implemented the behaviour using a macro, thanks for clearification!

**Comment by DidierLoiseau** [comment]
@sboesebeck As #239 has now been merged, you shouldn't need the macro any more :-)
