### ISSUE TITLE
Why is `NKRO_ENABLE` disabled by default?

### ISSUE THREAD

**Issue by lindhe** [jackhumbert/qmk_firmware#555]
Why is `NKRO_ENABLE` set to `off` by default? Is there any disadvantage I should know of, before considering enabling it? It feels like an all good thing, so I was baffled it was off by default.

Thanks for your great work with this repo; it's a joy reading through good documentation.

**Comment by ezuk** [comment]
In a nutshell, because it makes Windows cry. :) If you plug an NKRO-enabled keyboard into a machine running Windows, it may not recognize it.

Many thanks for your kind words on the repo and the docs! We've put a ton of work into those, so always makes me happy when people notice. :) Closing this issue for now, please reopen if you have any further questions.
