### ISSUE TITLE
keyboards/ergodox/ez/twimaster.c:9:22: fatal error: inttypes.h: No such file or directory

### ISSUE THREAD

**Issue by alaibe** [jackhumbert/qmk_firmware#802]
The error appear after a full upgrade on the system:
osx ugraded to sierra and brew update and upgrade

do you need any other log?

**Comment by tlvenn** [comment]
Same thing is happening for me with Sierra and Xcode 8

**Comment by tlvenn** [comment]
@jackhumbert any insight on this particular issue ? Thanks

**Comment by fredizzimo** [comment]
It's very hard to tell without knowing more details.

But my first guess is that it's somehow using the wrong compiler, or that the avr-libc isn't properly installed. The `twimaster.c` is the first file to be compiled, so that explains why it fails on that one.

I would try to  uninstall `avr-gcc` and `avr-libc` and then reinstall them. You might also get more support [here](https://github.com/osx-cross/homebrew-avr).

**Comment by alaibe** [comment]
indeed just a remove/install makes it work

thx for the help
